// message macros
#define PING 'N'
#define SIG 'S'
#define ACK 'A'
#define SEL 'L'
#define MOVE 'M'
#define BACK 'B'
#define FLOOD 'F'
#define EMPTY 'E'
#define BOOT 'b'
#define PROGRAM_AVAILABLE 'P'
#define PROGRAM_GET 'p'
#define PROGRAM_END 'X'
#define PAGE_SEND 'G'
#define PAGE_GET 'g'

